### ISSUE TITLE
example data fails to load

### ISSUE THREAD

**Issue by foobacca** [evildmp/Arkestra#57]
After getting to the point where manage.py will run at all, it fails to loaddata:

```
$ ./manage.py loaddata example_database.json
Problem installing fixture 'example_database.json': Traceback (most recent call last):
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 196, in handle
    obj.save(using=using)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 165, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/home/hamish/dev/thirdparty/Arkestra/example/.ve/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: Could not load cms.CMSPlugin(pk=1): cms_cmsplugin.changed_date may not be NULL
```

**Comment by okyame** [comment]
I think you should use develop branch and use example_14 for django 1.4.x and don't run  "python manage.py reset" contenttypes.

Or you've to use django1.3.x for example version

**Comment by evildmp** [comment]
I've tested on various operating systems, and various configurations, but I am not able to replicate any of the issues you're having, sorry.

In fact in every case following the steps at https://github.com/evildmp/Arkestra/blob/develop/docs/getting_started/installation.rst seems to work as it should. The exception has been when some sort of PyPI service issue arose; in that case simply running the `pip install` command again fixed it.

I'd like to know if what happens if you follow these steps exactly:
- virtualenv arkestra
- cd arkestra/
- source bin/activate
- pip install -e git+https://github.com/evildmp/Arkestra.git@develop#egg=Arkestra # install Arkestra & dependencies
- pip install -r src/arkestra/REQUIREMENTS.txt # install the things that pip can't do automatically
- cd src/arkestra/example_14 
- python manage.py syncdb --noinput # set up a new database; don't prompt for superuser
- python manage.py loaddata example_database.json # load the example database from the fixture
- python manage.py runserver 0.0.0.0:8000 # go!

You should be able simply to paste them into your terminal in one go. No prompts are involved.

**Comment by foobacca** [comment]
Ran through the steps and today it works. Thank you for your help.

**Comment by evildmp** [comment]
Great. Do drop onto #arkestra on irc.freenode.net while you're getting it going. It's also really helpful to me to see where the gaps are in the documentation are, or other problems.
